### ISSUE TITLE
[FR] Could fzf-tab builds the binary without zsh source code like past?

### ISSUE THREAD

**Issue by Vonfry** [Aloxaf/fzf-tab#414]
**Is your feature request related to a problem? Please describe.**
The released version use zsh sources to build the binary but the library isn't depended on zsh runtime according to `readelf -d`. The building process brings some unusual scripts when packaging in a distribution like nixos/nixpkgs#290612.

**Describe the solution you'd like**
Could it revert back to the non-released one?

**Describe alternatives you've considered**
If zsh library is necessary, could fzf-tab use built zsh library and includes files instead of source code?

**Comment by Aloxaf** [comment]
The problem is, there is no such thing like "zsh library". Zsh's module system is private, a module has to be built with the zsh source code.

The previous impletion is copying the source code of zsh 5.3.1 to this repository. Although I have never encountered any runtime issues, I'm still worried about it.
